### ISSUE TITLE
bbox node discards properties outside of msg.payload

### ISSUE THREAD

**Issue by s4ke** [yhwang/node-red-contrib-post-object-detection#2]
In order to keep properties for subsequent nodes it is useful to use properties outside of msg.payload. But since this node is sending `{payload: <imageData>}` this fails. The proper way for this would be to reuse the msg object and just change the msg.payload property.

**Comment by yhwang** [comment]
thanks for the feedback. I changed the code and published a new npm version of it. you can verify if that's what you need.

**Comment by s4ke** [comment]
Looks fine. It should be what I need.
