### ISSUE TITLE
Error: "Image object in invalid"

### ISSUE THREAD

**Issue by torinnguyen** [yhwang/node-red-contrib-post-object-detection#6]
BBoxImage is throwing error "Image object in invalid" & nothing is output from BBoxImage.
I have a debug node to check what's being send to it, but everything looks ok.
Please see attached screenshot.

My flow is taken from this [demo/tutorial](https://www.youtube.com/watch?v=bOdlPwWej98), nothing changed yet.

<img width="928" alt="2020-11-23 at 5 59 PM" src="https://user-images.githubusercontent.com/767320/99954829-f0f74700-2db5-11eb-8696-133450530352.png">

**Comment by torinnguyen** [comment]
I've figured it out!
1. The default inputs of BBoxImage is very misleading!!
2. And the error message is not helpful either.

It's much clearer to split [this line](https://github.com/yhwang/node-red-contrib-post-object-detection/blob/db69998bb41e61c5743acf71b2d96e51e2998ba8/src/bbox-image/index.ts#L153) into 3 different error messages.

<img width="726" alt="2020-11-23 at 6 07 PM" src="https://user-images.githubusercontent.com/767320/99955446-f1dca880-2db6-11eb-8b80-d40458440067.png">

**Comment by yhwang** [comment]
fixed here: https://github.com/yhwang/node-red-contrib-post-object-detection/commit/ab16442e866db0f6c174fd22bc86aab6cc299186
Thanks for the feedback!
